"""add feature_snapshot

Revision ID: 1b6c3f0d2105
Revises: 
Create Date: 2026-08-29 05:48:59.089693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6c3f0d2105'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_overrides_id'), table_name='overrides')
    op.drop_index(op.f('ix_overrides_transaction_id'), table_name='overrides')
    op.drop_table('overrides')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_decisions_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_transaction_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_config_history_id'), table_name='config_history')
    op.drop_table('config_history')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_razorpay_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('payload', sa.TEXT(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_id'), 'webhook_events', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=1)
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('razorpay_order_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('receipt', sa.VARCHAR(length=100), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_razorpay_order_id'), 'orders', ['razorpay_order_id'], unique=1)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('razorpay_payment_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('razorpay_order_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('bank', sa.VARCHAR(length=50), nullable=True),
    sa.Column('wallet', sa.VARCHAR(length=50), nullable=True),
    sa.Column('vpa', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('contact', sa.VARCHAR(length=50), nullable=True),
    sa.Column('error_code', sa.VARCHAR(length=100), nullable=True),
    sa.Column('error_description', sa.TEXT(), nullable=True),
    sa.Column('error_source', sa.VARCHAR(length=100), nullable=True),
    sa.Column('error_step', sa.VARCHAR(length=100), nullable=True),
    sa.Column('error_reason', sa.VARCHAR(length=100), nullable=True),
    sa.Column('raw_payload', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['razorpay_payment_id'], unique=1)
    op.create_index(op.f('ix_payments_razorpay_order_id'), 'payments', ['razorpay_order_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('config_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('config_snapshot', sa.TEXT(), nullable=False),
    sa.Column('version', sa.VARCHAR(length=20), nullable=False),
    sa.Column('changed_by', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_history_id'), 'config_history', ['id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('fraud_prob', sa.FLOAT(), nullable=False),
    sa.Column('fp_prob', sa.FLOAT(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('ltv', sa.FLOAT(), nullable=False),
    sa.Column('recommended_action', sa.VARCHAR(length=20), nullable=False),
    sa.Column('baseline_action', sa.VARCHAR(length=20), nullable=False),
    sa.Column('savings_vs_baseline', sa.FLOAT(), nullable=False),
    sa.Column('model_version', sa.VARCHAR(length=20), nullable=False),
    sa.Column('config_version', sa.VARCHAR(length=20), nullable=False),
    sa.Column('is_counterintuitive', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_transaction_id'), 'decisions', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_decisions_id'), 'decisions', ['id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user', sa.VARCHAR(length=100), nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('model_version', sa.VARCHAR(length=20), nullable=True),
    sa.Column('config_version', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_table('overrides',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('decision_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('original_action', sa.VARCHAR(length=20), nullable=False),
    sa.Column('overridden_action', sa.VARCHAR(length=20), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('analyst_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overrides_transaction_id'), 'overrides', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_overrides_id'), 'overrides', ['id'], unique=False)
    # ### end Alembic commands ###
